### ISSUE TITLE
Expose http.Client

### ISSUE THREAD

**Issue by enj** [kellydunn/golang-geo#28]
I am trying to use this library with Google App Engine which does not allow one to use the standard library to make HTTP requests.  I ran into a similar issue with a Twitter API, but was able to replace the `http.Client` since it was exposed in [the API](https://github.com/ChimeraCoder/anaconda/blob/master/twitter.go#L72).

I believe a change like this could allow for a similar capability:

```go
// This struct contains all the funcitonality
// of interacting with the Google Maps Geocoding Service
type GoogleGeocoder struct{
    HttpClient    *http.Client
}

...

// Issues a request to the google geocoding service and forwards the passed in params string
// as a URL-encoded entity.  Returns an array of byes as a result, or an error if one occurs during the process.
func (g *GoogleGeocoder) Request(params string) ([]byte, error) {
    if g.HttpClient == nil {
        g.HttpClient = &http.Client{}
    }
    client := g.HttpClient
    ...

```

Thoughts?

**Comment by kellydunn** [comment]
I think this could be a valuable addition, especially since you could swap out the http client to a mock client for testing purposes.

My only piece of feedback is to "constant-ize" the newly instantiated `&http.Client{}` as `DefaultHTTPClient`, like so:

```go
var DefaultHTTPClient = &http.Client{}

//...

func (g *GoogleGeocoder) Request(params string) ([]byte, error) {
  if g.HttpClient == nil {
    g.HttpClient = DefaultHTTPClient
  }
  client := g.HttpClient
}
```

Fwiw, I have a [list of features](https://github.com/kellydunn/golang-geo/blob/issue/97/ROADMAP.md) that I'd like to see in a `1.0.0` release of `golang-geo`, and this one could be on that list, as I see it being valuable for all geocoders to have this ability.

**Comment by kellydunn** [comment]
Great, It's on `master` now.  

@enj , want to try it out and let me know if there's anything missing?  If all is well, I'll close out this ticket :smile: :beers:

**Comment by enj** [comment]
Works like a charm, feel free to close.  Thanks for the help.
