### ISSUE TITLE
[Documentation] Could you please give a complete, executable minimal example?

### ISSUE THREAD

**Issue by MartinThoma** [kellydunn/golang-geo#31]
I don't have much experience with Go and I would appreciate a complete example which I can save and see if it works (that means I can see where I have to make changes).

See http://stackoverflow.com/q/28998709/562769 for my related question.

**Comment by MartinThoma** [comment]
I managed to get the code I needed:

```golang
package main

import (
	"log"

	"github.com/kellydunn/golang-geo"
)

func main() {
	p := geo.NewPoint(49.014, 8.4043)
	geocoder := new(geo.GoogleGeocoder)
	geo.HandleWithSQL()
	res, err := geocoder.ReverseGeocode(p)
	if err != nil {
		log.Println(err)
	}
	log.Println(string(res))
}
```

but I am still not sure how/why to use the (MySQL) database. Could you please help me with that? Which files to I have to create (config.yml in root folder?) and what do I have to write with your library?

**Comment by kellydunn** [comment]
Hello there! 

Just to clarify; you don't *need* to use a MySQL database in order to ReverseGeocode a point; The Database helpers are only necessary if you want to query points that you're storing on your database.  

From the [usage](https://github.com/kellydunn/golang-geo#usage) section of the README.md file:

> Keep in mind that you do not need to use SQL in order to perform simple Point operations and the only function that relies on SQL is PointsWithinRadius.

You only need to connect to a Database if you want to do some queries on a database of points you've previously connected.

A basic, minimal example for Reverse Geocoding a point would be the following:

```golang
package main

import (
    "log"
    "github.com/kellydunn/golang-geo"
)

func main() {
    p := geo.NewPoint(49.014, 8.4043)
    geocoder := &geo.GoogleGeocoder{}
    res, err := geocoder.ReverseGeocode(p)
    if err != nil {
        log.Println(err)
    }
    log.Println(string(res))
}
```
***

Also, in response to your stackoverflow question, the Google ReverseGeocode API gives you the ability to specify precision of reverse gecoding requests, but that functionality is not currently built into golang-geo.  More on that [here](https://developers.google.com/maps/documentation/geocoding/#ReverseGeocoding)

Admittedly, the response structs from all of the geocoder implementations could use a bit of love, and have some [scheduled changes](https://github.com/kellydunn/golang-geo/blob/issue/97/ROADMAP.md#geocoders-1) for v1 of golang-geo. 

Ideally, each geocoder could return more than just a string, but the requirements for the interfaces vary from api to api :\.  

However, if the feature of reverse geocoding and getting more precise information back is a requirement for you, I'd love to know!  It helps inform where the library should go. :)

**Comment by MartinThoma** [comment]
Hello Kelly,

Thanks for the detailed answer.

Getting more detailed information in Reverse-Geocoding would be great.

Best regards,
Martin

**Comment by kellydunn** [comment]
@MartinThoma :  I'll add it to the desired future featureset, as this is likely to cause some backwards incompatible changes.

Closing now, as it seems like the spirit of the ticket has been resolved.

Cheers :beers:

**Comment by sarnobat** [comment]
It might have been foolish of me to expect this to work in 2021. I guess Google has changed its API. Otherwise this tool would have been great.
