### ISSUE TITLE
Pointer to pointer?

### ISSUE THREAD

**Issue by enj** [kellydunn/golang-geo#37]
Sorry if this is a silly question.  On the following line:

https://github.com/kellydunn/golang-geo/blob/develop/google_geocoder.go#L122

You are getting a pointer value to the address of the struct, so a pointer to a pointer.  Is it necessary to have this for proper unmarhsalling or would a single pointer suffice?

**Comment by kellydunn** [comment]
you're correct, the following should suffice:

```golang
res := &googleGeocodeResponse{}
err := json.Unmarshal(data, res)
```
I can fix this now, if you'd like.

**Comment by enj** [comment]
Feel free to fix.

I am bit confused on how the `json.Unmarshal` function still works even with the extra indirection.

**Comment by drewwells** [comment]
This is very interesting and I wouldn't have expected `json.Unmarshal` would work in this case, but it does!

So under the covers `Unmarshal` work via reflection. You can think of that second argument to `json.Unmarshal` as a way to feed json with Type information on what to attempt to cast the byte slice to. For example, json.Unmarshal(data, &int{}) instructs json package to populate an int with the bytes stored in data.

Okay, so how is the value resolved? Over simplification, Interfaces are pointers to type information and the underlying value. So in either case of indirection, the same value is being pointed to whether it's `*type` or `**type`.

http://play.golang.org/p/LHo3k0oYr_

The final piece is how does json know that `*type` and `**type` are equivalent, when they are not? json does this work by inspecting the type data in retrieved via `reflect.TypeOf`. When a pointer is encountered, it unwraps this pointer via `reflect.Value.Elem()` [here](http://golang.org/src/encoding/json/decode.go#L332). The type has to be addressable which is why we must always pass pointer to `json.Unmarshal`. This reflection makes it possible to serialize structs like `type A struct{ int* Prop }`

There's a great writeup here about reflection: http://blog.golang.org/laws-of-reflection and links to more about interfaces here: http://research.swtch.com/interfaces

**Comment by enj** [comment]
Thanks for the detailed response @drewwells - so from I what i gathered from your explanation have the extra pointer does not have any negative consequences in this situation (i.e. it does not cause any subtle / hard to detect bugs).

**Comment by drewwells** [comment]
Not in this case apparently!

**Comment by kellydunn** [comment]
@drewwells :+1: for the explanation as well!  Definitely interesting to learn more about how reflection is used internally for language features :)

**Comment by kellydunn** [comment]
Closing, as #38 has been merged.
